server:
  port: ${SERVER_PORT}
  forward-headers-strategy: framework

spring:
  config:
    import: optional:file:credentials-dev.env[.properties]
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  liquibase:
    contexts: dev
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.yaml

  cloud:
    vault:
      uri: ${VAULT_ADDR}
      token: root
      kv:
        enabled: true
        backend: secret
        default-context: card-encryption

sender:
  mail: ${SENDER_MAIL}
  password: ${SENDER_PASSWORD}
  smtp:
    host: smtp.yandex.ru
    port: 465
  email-replace: '@EMAIL@'
  token-replace: '@TOKEN@'

ipstack:
  access:
    key: ${IPSTACK_ACCESS_KEY}

jwt:
  secret: ${JWT_SECRET}
  token:
    time-expiration: 1000000000
    access-expiration-seconds: 900 # 15 минут
  token-refresh:
    time-expiration: 10000000000000
    refresh-expiration-seconds: 604800 # 7 дней

card:
  expiration-years: 3

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /docs/openapi.yaml
  api-docs:
    enabled: true
    path: /v3/api-docs

# Настройки логирования (JSON для ELK в prod профиле)
logging:
  level:
    root: INFO
    com.example.bankcards: DEBUG